### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by fichestrati** [christian-oreilly/spinkyDemo#1]
Hello,

We would like to work with your spindle and complex K detection program.
We work with "Open Source" tools as part of a luminotherapy project.
We have our EEG data and we want to know how to put it in place with your "Spinky" tools.

Can you tell us how to install and use this software in our project.

Sincerely, projet de recherche et d'innovation,
SOGETI France.

**Comment by christian-oreilly** [comment]
Hi,

Did you read the readme file (https://github.com/christian-oreilly/spinkyDemo)? How to use the package is described there. If there is something not clear, could you formulate some questions please?

Best,

Christian
